snabbdom.js

Good work.

---

test/core.js

Nice implementation !
However just wanted to warn you that your patching algorithm doesn't work well when playing with keyed & non-keyed virtual nodes, there's probably still a minor glitch somewhere.

Failed spec when using mixed keyed & non-keyed virtual nodes.

---

examples/hero/build.js
examples/hero/index.html
modules/hero.js

These commits make the hero module more flexible and easier to use.
It now handles inherited styles, text alignment, and many other situations with less friction.
The official example has been hacked to work with the new module as well, though it could be simplified greatly.

Hero module updates

---

snabbdom.js
test/core.js

Added a failing test case and the change to fix it. For #64.

Should be able to patch nodes created inside an iframe.

---

.gitignore
snabbdom.js
test/attachto.js
test/core.js
test/eventlisteners.js
test/style.js
test/thunk.js
thunk.js

did some final cleanups.
This works fine for my use cases and can be released as far as I can tell.

small cleanups

---

.gitignore
snabbdom.js
test/attachto.js
test/core.js
test/eventlisteners.js
test/style.js
test/thunk.js
thunk.js

Continued a little bit sprat's work on making root-node changes work correctly, including calling the remove hook (important for doing animations).

patching root node

---

htmldomapi.js
snabbdom.js

resolves https://github.com/paldepind/snabbdom/issues/47

dom api implementation

---

modules/dataset.js
test/dataset.js
test/index.js

new dataset module and module tests as discussed in #90

Pr dataset module

---

README.md

Add documentation for the structure and properties of a virtual
node used by snabbdom and created by h().

docs(README): add virtual node documentation

---

README.md

Most references to vnode were all lowercase so I standardized on this.  Fixed some small typos and made a few editorial adjustments.  Feel free to take any, all or none of these suggestions (Though I do recommend the typo fixes!)

Some minor cleanup

---

package.json
type-definitions/snabbdom.d.ts

Add typescript definitions for consumption of other libraries and users that prefer typescript :)

chore(TS): add typescript definitions

---

README.md

fix style example in README.md

---

src/modules/style.ts

`String.prototype.startsWith` is in ES2015 specification and is not ready for some devices.

Fix compatibility issue of String.prototype.startsWith

---

src/snabbdom.ts
test/core.js

Changed the patching algorithm to support `null`/`undefined` children as I described in #226.
This should make the core algorithm slightly more resilient, but maybe changing the `h` function would be simpler (as was originally proposed). :-)
Tell me your thoughts. Maybe this needs more tests? Lazily copied the one @staltz wrote.

Support for null/undefined children

---

README.md

[Tweed](https://tweedjs.github.io) is a UI framework that uses an Object Oriented approach to building reactive UIs. It uses Snabbdom for rendering both client side and server side.

Add Tweed to the list of example projects

---

src/modules/attributes.ts
test/attributes.js

Set boolean attributes correctly according to spec

---

README.md

Cyclow is a new reactive frontend framework for JavaScript I've created. It uses Snabbdom. Please, consider add it to "Structuring applications" section. Thank you.

Add Cyclow framework to README

---

README.md

Could you add Tung to "Structuring applications" section?
Thank you.

Add Tung to README

---

src/helpers/attachto.ts
src/modules/attributes.ts
src/modules/class.ts
src/modules/dataset.ts
src/modules/eventlisteners.ts
src/modules/hero.ts
src/modules/props.ts
src/modules/style.ts
src/vnode.ts

Is this any kind of reasonable?

type VNode props (fixes #264)

---

src/modules/style.ts

Make delayed and remove property optional

---

README.md

- As above, extended README.md contents for a description and an example

Added a missing snabbdom/tovnode piece of documentation

---

dist/snabbdom-dataset.js
gulpfile.js

Currently the dataset module doesn't get a distribution build. This pull request adds the necessary gulp step and the built file.

Also create a dist build for the dataset module

---

src/h.ts

Sorry for the delay in creating this small fix. Here's the PR for #361.

Fix for issue 361

---

README.md

Thanks for build this great library.
Mark Text is a markdown editor build on snabbdom.

Update: add Mark Text to README

---

README.md

Thanks for making snabbdom such a pleasure to use! It does everything I want and more in a vdom library.
[`puddles`](https://github.com/flintinatux/puddles) is a tiny framework I've put together to make the Redux pattern easy, without all of the boilerplate.  Snabbdom makes the magic happen, and `puddles` just handles the Redux bits.

Add puddles to README.md

---

README.md

snabbdom-looks-like is a small test utility to check if a vdom tree matches a template vdom

Add snabbdom-looks-like to README

---

README.md

Explain insertBefore in README

---

src/modules/style.ts

Binding raf to window resolves the error.

Fix for #360 error in IE/Edge

---

src/thunk.ts
src/vnode.ts

Hi, I saw a small part of the source code that I could optimize
If you feel ok，Can you merge the branch ? 
Thank ~

refact: Small part of the grammar optimization

---

README.md

Suggested adding Pureact which only has one dependency - Snabbdom.

Added Pureact

---

package-lock.json

chore: add a package-lock.json

---

.travis.yml
package.json

#399 was not finished yet, not this PR finishes the configuration

Finish CI configuration

---

package.json

fix: npm test script `karma start`

---

.travis.yml
karma.conf.js

I saw that in master the setup is broken, we had the same issue in the cycle repo lately. This is the fix we used

Remove travis browserstack addon to fix HTTP error

---

package-lock.json
package.json

test: update karma-firefox-launcher

---

browserstack-karma.js

This reverts commit 7e09d27f5680de198b7b363f574f531f4f1aa180.

Revert "Disable failing browsers in CI configuration"

---

package.json

fix: npm script prepublish -> prepublishOnly

---

browserstack-karma.js

ci: disable failing browsers

---

README.md

docs: maintenance policy

---

README.md

Removed broken link of  Benchmark from readme

---

.eslintrc.js
package-lock.json
package.json
src/snabbdom.ts

Updates dependencies to the most recent version of TypeScript.
Tweak/refactor a bunch of things in `snabbdom.ts`. Most of the changes are related to using new features in JavaScript/TypeScript.
I won't go through each change but please comment if there is anything that does not look like an improvement :smile:

Update TypeScript, refactor

---

.travis.yml
README.md
examples/carousel-svg/README.md
package-lock.json
package.json

docs: introduce remark and some readme tweaks

---

.travis.yml
commitlint.config.js
package-lock.json
package.json

chore: introduce commit linting

---

package.json
src/test/jsx.tsx

style: lint .tsx

---

karma.conf.js

test: run jsx test

---

src/snabbdom.ts

chore: merge statement

---

.eslintrc.js
perf/benchmarks.js
src/h.ts
src/snabbdom.bundle.ts
src/test/attachto.ts
src/test/attributes.ts
src/test/core.ts
src/test/dataset.ts
src/test/eventlisteners.ts
src/test/htmldomapi.ts
src/test/style.ts
src/test/thunk.ts

- import/newline-after-import
- dot-notation
- import/first
- no-undef

style: four eslint rules enabled

---

README.md

docs: rm unimplemented unmounting by 2nd arg null

---

karma.conf.js
package-lock.json
package.json

chore(test): karma-webpack, test both CommonJS & ES modules

---

browserstack-karma.js
src/test/attributes.ts
src/test/core.ts
src/test/style.ts

test: workaround IE11 defficiencies

---

browserstack-karma.js
src/test/dataset.ts

test: enable IE10

---

commitlint.config.js
package-lock.json
package.json

test: use commitlint-config-awesome

---

karma-benchmark-reporter.js

fix(benchmark): do not print title if did not run

---

src/modules/class.ts

perf(class): prevent redundant calls to classList.remove

---

karma.conf.js

chore(ci): increase browser concurrency to 5

---

.travis.yml
commitlint.config.json
package-lock.json
package.json

dx(commitlint): fix and enable in CI

---

package.json

ux(exports): remove package.json main field

---

package.json

ux(package): no module field

---

package.json

ux(exports): main export provided

---

README.md
commitlint.config.json

ux(docs): fix wrong module import paths

---

.versionrc.json
CONTRIBUTING.md
commitlint.config.json
package-lock.json
package.json

Also set up a documented release process.
Fixes #670.

ux(docs): provide a release changelog

---

README.md

ux(docs): add an OpenCollective banner to readme

---

commitlint.config.json
examples/carousel-svg/index.js
examples/hero/index.js
examples/reorder-animation/index.js
examples/svg/index.js

fix(examples): example import paths

---

CONTRIBUTING.md
commitlint.config.json

co-authored-by: Shahar Dawn Or <mightyiampresence@gmail.com>

docs(github): use refs/pull in allowing ci

---

package.json

fix(package): update urls paldepind -> snabbdom

---

CONTRIBUTING.md
mark-pr-head-as-trusted.cjs
package-lock.json
package.json

co-authored-by: Shahar Dawn Or <mightyiampresence@gmail.com>

chore(github): mark pr head as trusted script

---

README.md
commitlint.config.json

docs(style): `transition-property:all` not supported

---

src/test/unit/eventlisteners.ts

test(eventlisteners): fix listener context HTMLElement -> VNode

---

package-lock.json
package.json

fix(deps): add regenertor-runtime to devDeps

---

src/package/modules/eventlisteners.ts
src/test/benchmark/core.ts
src/test/unit/eventlisteners.ts

feat(eventlisteners): add missing mult. listeners type

---

src/package/modules/eventlisteners.ts
src/test/tsconfig.json
src/test/unit/core.ts

feat(eventlisteners): relax custom event listener type

---

src/package/modules/eventlisteners.ts
src/test/benchmark/core.ts
src/test/unit/eventlisteners.ts

feat(eventlisteners): add types for VNode in listener

---

examples/carousel-svg/index.js
examples/hero/index.js
examples/reorder-animation/index.js

Hi , when I was learning snabbdom, I ran the examples, but found that it was a project based on the old grammar, and some functions could not be run.
I adjusted the example according to the new grammar. Can better help everyone learn

chore(examples): update examples

---

src/package/init.ts

The bug introduced by 39c9da4615d248265ff8de376a95adab799ca981 on #829 and reported by @alfonsogarciacaro on https://github.com/snabbdom/snabbdom/pull/829#discussion_r587475354.

Fix node similarity checking bug

---

.eslintrc.js
examples/hero/hero.js
examples/hero/index.js
src/index.ts
src/vnode.ts

As discussed, it is too specific. I moved it to the examples instead

Remove the hero module

---

examples/hero/index.js
package-lock.json
package.json
serve.json

`npm run example` run example locally and make debugging a lot simpler.
lint fail and fixed by #981

chore(tools): enable npm run example

---

src/h.ts
src/thunk.ts
src/tovnode.ts

Fix SVG bugs

---

src/tovnode.ts
test/unit/core.ts

feat: toVnode is support dataset

---

src/tovnode.ts
test/unit/core.ts
test/unit/dataset.ts

bug fix: toVNode use datasets bug dataset module use dataset

fix: datasets -> dataset

---

README-in_HN.md
README.md

Hello,
I've created this pull request to address the feature request for adding support for the Hindi language to this library. This enhancement is crucial to improve accessibility and user experience for Hindi-speaking users.
**Use Case:**
The library has been gaining traction in India, and it's evident that supporting Hindi will significantly enhance reach and user satisfaction.
**Requested Features:**
- Addition of Hindi language support in the documentation
I believe this feature will not only broaden the audience but also boost user engagement.
I welcome your feedback and any suggestions you may have. Thank you for considering this pull request.
Best regards,
Sundaram Sharma

Feature Request: Add Support for Hindi Language

---

src/h.ts
src/tovnode.ts

per https://github.com/snabbdom/snabbdom/pull/1057, use startsWith to optimise the detection of data and svg names
this PR would satisfy two outstanding PRs
1. https://github.com/snabbdom/snabbdom/pull/1037, optimize data attribute
2. https://github.com/snabbdom/snabbdom/pull/1033, optimize svg selector

feat: optimise detection of data and svg names

---

src/init.ts

this PR applies formatting to src/init.ts and when it is merged, the text nodes patch PR https://github.com/snabbdom/snabbdom/pull/1062/files can be rebased on master to reduce noise in that PR

chore(refactor): prettier --write src/init.ts

---

.eslintrc.json
.prettierignore
README-in_HN.md
README-zh_CN.md
README.md
package.json

This PR removes prettier-formatted trailing-comma and removes the .prettierignore (prettier continues to ignore build and coverage directories after the file is removed.

chore(tools): remove un-needed dot-files; .prettierignore

---

package-lock.json
package.json
test/unit/core.ts

Removes lodash-es devdependency, ~622kB
* https://packagephobia.com/result?p=lodash-es

chore(tools): remove devdependency lodash-es; used once, ~622kB

---

web-test-runner.config.js

related https://github.com/snabbdom/snabbdom/pull/1088#issuecomment-1834480560
link to documentation https://modern-web.dev/docs/test-runner/cli-and-configuration/

chore(test): increase browserStartTimeout, reduce frequent pipeline timeout failure

---

.github/workflows/lint.yml
package-lock.json
package.json

This PR enables prettier format check at the lint job, enforcing prettier format for PRs

chore(test): enforce prettier format for pull requests using lint ci job

---

src/init.ts
test/unit/core.ts

Copy-pasted changes from @tokichie https://github.com/snabbdom/snabbdom/pull/347 re-applied to the current master branch

fix: allow innerHTML to replace non-empty node, credit @tokichie

---

package-lock.json
package.json

This works around an upstream issue: https://github.com/GervinFung/ts-add-js-extension/issues/82
ISSUES CLOSED: #1087, #1102

fix: work around bug in ts-add-js-extension

---

src/vnode.ts

we can use PropertyKey instaed of key list

refactor: use PropertyKey instaed of key list
