snabbdom/snabbdom

- README.md
- modules/attributes.js
Attributes are added and updated using `setAttribute`. In case of an attribute that has been previously added/set is no longer present in the `attrs` object, it is removed from the DOM element's attribute list using `removeAttribute`. 
In the case of HTML boolean attributes (.e.g. `disabled`, `hidden`, `selected` ...) attributes are removed if the attribute value is falsy in the JavaScript sens.
> module for setting element attributes

- README.md
Also, I am not clear when you would use the destroy vs remove style hook. It seems the remove hook is preferred because it guarantees the animation finishes before element removal? Why would you use the destroy hook - maybe a sentence should be added to the readme on this - unless the destroy hook is no longer supported?
> fix style transition examples in README

- snabbdom.js
This pull request makes it possible to run a patch inside another patch. Previously the variable `insertedVnodeQueue` was shared between patch-runs. This commit makes the variable local to the current patch-run.
The use case is custom elements running snabbdom that render other custom elements that might be using snabbdom.
I checked the min+gzip size and found the previous size to be 1403 bytes and the new 1423 bytes.
> Make it possible to run a patch inside another patch

- examples/hero/build.js
- examples/hero/index.html
- examples/hero/script.js
The hero animation example was not showing correctly (width would be 100% of device width, even on desktop).
The CSS was targeting the app container, which gets replaced as soon as the app starts.  I changed the CSS to target the wrapper div which is part of the vdom, and it looks right again.
> Fixed hero example to account for #container being overwritten.

- modules/style.js
When using snabbdom with webpack, the webpack output file is in strict mode, and that would cause error:
> Uncaught ReferenceError: requestAnimationFrame is not defined at ...
This pull request fixed it.
> Fixed 'Uncaught ReferenceError'

- modules/class.js
- modules/props.js
- modules/style.js
- test/core.js
- test/style.js
I realise that this may have a minor performance impact, but it does fix a lot of render issues when comparing very different vnode structures.
It may also need to be done to on-* events as well.
> Ensure that class, props and style artefacts are not left after re-render

- snabbdom.js
- test/core.js
When a vnode has a `text` property  and is patched with a vnode with no `text`, the text node is never removed. Similarly, when a vnode has a `text` property and is patched with `children`, the text node created via the old `text` property isn't removed, so you end up the children being appended after the extra text node.
```html
<div>One</div>
``` 
becomes 
```html
<div>One<div>Two</div><span>Three</span></div>
```
instead of 
```html
<div><div>One</div><span>Two</span></div>
```
which, I believe, is unexpected behavior. This adds some test cases to catch this and the fix.
> Make sure we remove a single text node when patching it's parent element.

- snabbdom.js
`Element.ELEMENT_NODE` is non-standard and undefined in phantomjs.
Updating to use `Node.ELEMENT_NODE`.
References:
- MDN Element: https://developer.mozilla.org/en-US/docs/Web/API/Element
- MDN Node.nodeType: https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeType
> Fix element node detection in patch

- modules/props.js
DOM `INPUT.value` should never be updated when it matches the new vnode.
This fixes issues where typing into an INPUT with a sync event handler cause a render (such as for validation feedback) where setting `INPUT.value` also pushes the cursor to the end of the input.
> Fix cursor jumping to the end of "controlled" inputs

- .gitignore
- snabbdom.js
- test/attachto.js
- test/core.js
- test/eventlisteners.js
- test/style.js
- test/thunk.js
- thunk.js
I've fixed a bunch of problems with thunks, but it was harder than I thought. I encountered many problems:
- many tests assumed that the root node would never be replaced. But, if I remember correctly, I needed to mutate the root node for thunks, so I removed this limitation. I had to change many tests to remove the invalid assumptions.
- some tests use a real DOM node as second parameter of `patch`. I'm not sure if it's a valid use case. In doubt, I didn't change the test cases, but it's probably broken! (and was probably already broken). I think we'd better not support that at all, it's just a matter of removing the instanceof check for vnode in my merge request.
- I think it still doesn't work with nested thunks, i.e. thunks returning thunks. It may not be very difficult to implement …
> Thunks fixes

- .gitignore
- snabbdom.js
- test/attachto.js
- test/core.js
- test/eventlisteners.js
- test/style.js
- test/thunk.js
- thunk.js
This PR contains the great work by @sprat and @kay999. 
* I've fixed a few tiny things and merged the changes into a branch based on the current master.
* All tests now pass. I've fixed the tests where an element was incorrectly passed to `patch` as a second parameter as noticed by @sprat.
* I've added a test case for what I think is the problem that @kay999 fixed.
* Now `destroy` and `remove` hooks are only invoked when the replaced root has a parent element. As far as I can tell this covers all practical cases. Furthermore it made it possible to get rid of the quite ugly usage of a dummy element.
Does this still work for you @kay999? If yes I'll merge this and do a release.
Btw, am considering a new approach to thunks that should support nesting in a simpler way.
> Replace root

- modules/hero.js
- modules/style.js
Doing `window &&` does not achieve the expected behavior, it instead crashes with an error `ReferenceError: window is not defined`. This fix is simple and necessary for server-side rendering.
> Fix safety check for requestAnimationFrame

- snabbdom.js
require call should follow convention, even though the node loader won't complain either way.
> reference htmldomapi by module name

- snabbdom.js
- test/thunk.js
- thunk.js
This is a new thunk implementation.
When a thunk is inserted in a virtual DOM tree a dummy thunk is placed instead of an actual vnode. However during patching an actual node will have to be associated with the thunk. Either a vnode from the previous thunk or one obtained by calling the function associated with the thunk. The old thunk implementation worked by setting a property `vnode.data.vnode` on thunks during patching. This turned out to have the disadvantage that everything in the code that uses a `vnode` whould have to check the property `vnode.data.vnode` to see if that was actually the real vnode. Doing that increased the complexity and was never done properly.
The new implementation instead overrides all properties in the thunk so that it becomes an actual proper vnode. I tried …
> New thunk implementation

- h.js
In my app, I am wrapping calls to `h` with another helper. This helper passes through args to `h` after applying some logic, as in:
```js
function helper(first, second, ...rest) {
// ... logic ...
h(first, second, ...rest);
}
```
Checking `arguments.length` causes this helper to fail, since it is just passing through values, so there could be only 2 "truthy" arguments, but `h` would receive `h(first, second, undefined)`, breaking the argument processing in `h`.
Switching to truthy checks appears to solve this and preserve previous behavior. What do you think of this?
Thanks for working on this library! :smile:
> h: Test args for defined values instead of args.length

- modules/eventlisteners.js
In the current version, a event-listener is never removed, which leads to problems in certain use cases. This patch fixes this.
(I hope I got everything correct, because I made this changes online).
> eventlisteners should work if a listener is removed

- modules/attributes.js
- modules/class.js
- modules/dataset.js
- modules/eventlisteners.js
- modules/props.js
- modules/style.js
Currently for each module, on every update, for every node, empty objects are allocated, enumerated and iterated over regardless of whether that node has data for the module or not.
Returning early prevents useless object allocation and `for ... in` enumeration, which should result in better memory usage and more efficient patching.
I'm observing around 10% fps increase in the dbmon benchmark.
> Return early in module update functions

- h.js
- test/core.js
Hi there,
This PR adds a new condition to the `addNS` function to halt recursion if it encounters the `foreignObject` SVG element. The result of this is that embedded HTML elements now retain the correct namespace (`http://www.w3.org/1999/xhtml`) and should render correctly inside the SVG parent.
I've appended a few new assertions to the existing namespace test case, but please let me know if there is a smarter way to do any of this! 
P.s I had some troubles running the tests whereby the page continuously reloads in both Firefox and Chrome. I was able to see the new tests passing/failing as i'd expect, but I'm not sure if there's something going wrong with the test runner?
Thanks 😄
> 126 svg foreignobject

- README.md
Using SVG elements with classes has two issues due to className being readonly for these elements and some browsers not accepting classlist on them. Added details and workaround.
> Added details on using classes with SVG

- testem.json
Hi there,
This PR should prevent the endless reload loop I was seeing while running the tests (as mentioned in https://github.com/paldepind/snabbdom/pull/133)
It looks like running the tests (first via `npm test`) tells testem to browserify the test files (during `before_tests`) and create the output file in the `test` dir, which triggers the watcher from `src_files` causing the tests to run again and so on...
I've moved the browserify output file to outside of the watched dir so its generation doesn't cause the test runner to restart. This appears to stop the reloading issue and the test runner now works as I expected, reloading the tests when a change to a spec file is made.
Please let me know if this is not what you expect 😄
> Prevent test runner from continuously reloading

- modules/eventlisteners.js
- test/eventlisteners.js
Key differences:
* Full backward compatibility
* Improved adding/removing event listeners to/from real DOM node
* Using unified function as real event listener per node
* Access to virtual node from event handler through `this`
* Support for multiple listeners for same event
* No problems with shared handlers
> New implementation of eventlisteners module

- snabbdom.js
- test/core.js
Previously, patch(element, vnode) would create a new element every time
for the top-level element, unless the top-level vnode had no id and
className. This is because emptyNodeAt() would create a vnode with sel
equal to the element's tagName, NOT including id and className.
This seems to be just a small fix, however this fix was crucial to get
Web Components (custom elements) working with Cycle.js, because the
custom element's "create" callback was being called infinitely and
recursively, because snabbdom was creating the top-level element every
time, even if the sel of oldVNode and vnode were supposed to be the
same.
> Fix patch() so that the root is patched instead of recreated

- .gitignore
- modules/attributes.js
- test/attributes.js
- test/index.js
Currently boolean element attributes have a special behavior: they are omitted if the value for the attribute key passed in an `attrs` object is falsy.
For performance reasons all the boolean attributes are stored in a native object that acts like a Map. However, objects constructed in a literal form have its prototype set to Object.prototype, so property lookup operation `booleanAttrsDict[key]` will also check for all the properties up on the prototype chain, including Object.prototype.
This makes the attributes with the same names as Object.prototype properties and methods (like `constructor`, `valueOf`, `toString`, etc.) behave like boolean attributes.
This change makes the boolean attributes dictionary prototype-less ([explanation](http://www.2ality.com/2013/10/dict-pattern.html)) to …
> Don't treat Object.prototype properties as boolean attributes

- modules/attributes.js
- test/attributes.js
Per https://github.com/cyclejs/cyclejs/issues/461, this update uses setAttributeNS so that attributes such as "xlink:href" can be used safely.
> Support namespaced attributes

- src/h.ts
- test/core.js
Figured it was easier to create a new branch/PR now that the codebase is rewritten in TS.
Text from the previous PR:
---------------
For two reasons:
- Convenience (virtual-dom does it too)
- As it stands, it's very hard (impossible if you account for people's potential custom modules) to type the `h` function correctly as typescript uses structural typing and the data object being lots of optional things (it will typecheck just fine if you specify them, but the compiler is clueless if you don't), an Array or VNode could pass for an empty data object just fine. If we can't encode it, allow it!
That kind of typing is actually ambiguous. I use overloads myself:  https://github.com/AlexGalays/kaiju/blob/master/src/main.d.ts#L283
If someone tries to write (as of today, by mistake. It happened …
> Allow h(sel, data, node) and h(sel, node) shortcut notations

- src/snabbdom.ts
- test/core.js
I've created a [pull request](https://github.com/snabbdom/snabbdom/pull/184) days before, but found that is not complete. And the [vdom code of vue](https://github.com/vuejs/vue/blob/dev/src/core/vdom/patch.js#L308) should explain this problem.
> Fix bug of updating one child with same key but different sel.

- src/helpers/attachto.ts
- src/is.ts
- src/snabbdom.ts
- src/vnode.ts
I took a stab at removing some of the casting in the TypeScript port.
Mostly by replacing `isDef(foo)` with `foo !== undefined` because the TS compiler don't understand that `isDef` does `undefined`-checking.
I've removed some other ones by tweaking the types slightly.
I managed to get rid of 19 casts and a few `any`s.
> Tweak types, reduce casting

- README.md
- src/modules/style.ts
- test/style.js
- tsconfig.json
Take a look to this example (using cyclejs):
https://jsbin.com/guhevu/7/edit?css,js,output
It would be nice to have that api on the style module.
Inspired by these talks:
- [Lea Verou - CSS Variables: var(--subtitle);](https://youtu.be/2an6-WVPuJU?t=46m43s)
- [David Khourshid: Reactive Animations with CSS Variables](https://www.youtube.com/watch?v=lTCukb6Zn3g)
> Add support for css variables

- src/h.ts
- test/core.js
The check at https://github.com/snabbdom/snabbdom/blob/f79af828/src/h.ts#L37
is too loose, and ends up adding the svg namespace to elements with
tagNames such as `svg-icon`, which prevents web components lifecycle
callbacks from firing.
Added test cases for the custom element case as well as longer svg selectors
(e.g. `svg#my-id`) which are currently untested.
> Fix Custom Element creation when tag name begins with 'svg'

- src/helpers/attachto.ts
- src/htmldomapi.ts
- test/htmldomapi.js
- test/index.js
In IE11 children and parentElement are undefined for SVG elements. 
Instead childNodes and parentNode should be used.
> use parentNode instead of parentElement

- package.json
- src/h.ts
- src/helpers/attachto.ts
- src/htmldomapi.ts
- src/modules/module.d.ts
- src/snabbdom.ts
- src/vnode.ts
This PR uses two nifty new features from TypeScript 2.1. `keyof` and mapped types to typecheck the stored module hooks in `cbs`.
I also changed the type of the `data` argument to `h` from `any` to `VNodeData`. I think that is better as it assures that "known" properties on the data object are type checked.
A few other things are tweaked as well.
> Use `typeof`

- src/modules/attributes.ts
- src/modules/class.ts
- src/modules/dataset.ts
- src/modules/props.ts
- src/modules/style.ts
- test/attributes.js
- test/core.js
- test/dataset.js
- test/style.js
Modules are already applying some opt-out rules, but when the specific piece of data used by the module is the same, a couple of unnecessary `for-in`, plus few conditions were evaluated. This is particularly useful if any kind of memoization is used during the creation of the vnode, which is user-land code.
> [perf-optimization] skip unnecessary work in modules when possible

- README.md
I created a new project today called [snabby](https://github.com/jamen/snabby).  It is experimental, so I apologize if this list is for vetted modules. 
It basically allows you to create virtual nodes using template strings. It also has a `snabby.update` function inspired from how [`yo-yo`](https://npmjs.com/yo-yo) does things.
```js
// Create some vnodes:
var foo = snabby`<div>Hello Earth</div>`
var bar = snabby`<div>Hello Mars</div>`
// Patch to DOM
snabby.update(document.body, foo)
// Patch update
snabby.update(foo, bar)
```
I was hoping to attract some collaborators, and maybe turn it into something more "official" (whatever that means).  Disclaimer that I'm new to Snabbdom, so this is also a learning process for me.
I was initially inspired because of a framework called …
> Add reference to "snabby"

- src/htmldomapi.ts
- src/snabbdom.ts
- test/core.js
Like some other users in #142, I need to be able to create comment nodes.
This PR adds this feature using similar syntax as proposed before:
```js
h('!', 'comment content')
```
Is a better place for the `vnode.text = ''` in `createElm`?
> Add ability to create comment nodes

- .gitignore
- src/htmldomapi.ts
- src/tovnode.ts
- src/vnode.ts
- test/attributes.js
- test/core.js
- tsconfig.json
This commit addresses issue #167. 
Previously, in snabbdom v0.5.0, patch(element, vnode) would always create a new element for the root. This resulted in problems with custom elements (web components), and was fixed in commit c091c59.
However, that commit resulted in bug #167. This meant that snabbdom would have bugs with server-side rendering, where the root element would be non-empty (it has many children, rendered on the server-side as HTML), and the client-side rendering should reuse those existing children (or clear all the children and recreate them again in patch()).
This commit introduces the function toVNode(elm) that deep-converts an element (and its tree) to a VNode (and its tree), that is separately imported and used before calling patch(). toVNode(elm) will look at the …
> Introduce toVNode() to reconstruct root element as vnode 

- src/modules/dataset.ts
At least IE10 does not support the elm.dataset property, so we must use
elm.removeAttribute and elm.setAttribute instead.
I found this issue when testing Cycle.js against IE10.
> Fix dataset module to support old browsers

- src/snabbdom.ts
I have noticed that there is a slightly different between the create and update workflows, specifically, during the update process, the element itself is updated first (by calling the update callback), then the children collection is updated, but during the creation, this process is the inverse, and all children are created before the element itself is updated (by calling the create callback).
Considering that for the majority of the modules, the create and update hooks are the same, it makes it difficult to predict if the children collection can still be used in any way. Think of a vnode with a hook to validate, and sanitize the children collection, in which case the process will work only when patching against an existing tree, but not when a new tree is created.
The change itself seems …
> Create element workflow should align with update element workflow

- src/tovnode.ts
- test/core.js
I've added the change to fix https://github.com/snabbdom/snabbdom/issues/252 and added a test that threw the type error before the change and now passes.
This should also fix https://github.com/cyclejs/cyclejs/issues/531
> fix tovnode to ensure text elements can be removed

- src/modules/attributes.ts
- test/htmldomapi.js
- Avoid call to split and use a object lookup instead
- Simplify the code for svg namespaced attributes
> Performance improvement for attribute patching:

- README.md
fixes #248
As snabbdom-jsx and snabbdom-jsx-babel hadn't had an update in 7 to 8 month and expecially the former has several bugs I would not advertise to use them.
Snabbdom-pragma works more reliable and thanks to a few PRs by me it works just as good with svg as it does with html
> Replace snabbdom-jsx with snabbdom-pragma

- src/snabbdom.ts
- test/core.js
Fixes #217 
Use `elm.setAttribute('class', ...)` instead of `elm.className = ...` to make it work in SVGs.
Not absolutely sure it does not have implications, but `setAttribute` is in scope here since we are talking about Elements creation (and not mutation, in which className is recommended).
Another option would be to write in the attribute `className.baseVal` when in SVG namespace.
> Fix error when class is set by vdom selector in SVG

- src/h.ts
Required now that #226 is implemented.
> Update `h` signature; children nodes can now be `undefined` or `null`

- src/tovnode.ts
- test/style.js
Comment nodes when converted to VNode were lacking `vnode.data` and `vnode.elm`, which in turn would break use cases with modules such as the style module (Which assumed `vnode.data` to be truthy). Since `toVNode` is used as an initial step (e.g. for server-side rendered content), there is no reason to not provide `vnode.elm` since that vnode may be used as the "oldvnode" during patch. Also, because comment vnodes have the `'!'` sel, most logic in snabbdom that detects a truthy `sel` will also assume a truthy `data` field. It is easier to build the comment vnode with those fields than to modify all the logic elsewhere in snabbdom. Probably also better for performance.
This fix in snabbdom is important for this issue in Cycle.js: https://github.com/cyclejs/cyclejs/issues/561
> Fix toVNode() for comment nodes, lacking some fields

- src/snabbdom.ts
- src/vnode.ts
Because actually it can be undefined:
https://github.com/snabbdom/snabbdom/blob/4adbd971cba738c38d6158b38fdb81a6509d1553/src/vnode.ts#L44
@mightyiam
> VNode key property can be undefined

- src/modules/attributes.ts
Remove draggable from boolean attributes enum.
"This attribute is an enumerated one and not a Boolean one. This means that the explicit usage of one of the values true or false is mandatory and that a shorthand like \<label draggable>Example Label\</label> is not allowed. The correct usage is "\<label draggable="true">Example Label\</label>."
> PR for issue #262 (remove draggable of boolean attributes)

- src/modules/dataset.ts
in Safari, when it is `use strict`, if the dataset property is removed in DOM
deleting it again will cause an error
closes #309
> fix(dataset): check if property exist before deleting

- src/modules/attributes.ts
- test/attributes.js
_note: this change is not backward compatible_
* if the attribute `foo` is set to `true` in the `vnode.data.attrs`, it will appear in the dom as `<div foo>`
* if the attribute `foo` is set to `false` in the `vnode.data.attrs`, it will not appear in the dom as `<div>` 
* snabbdom does not provide any validation, nor a whitelist of boolean, that's a responsibility of the creator of the vnode.
* falsy values will be considered as regular attributes, and the value will be casted to string, just like html.
* if the attribute `foo` is set to `"false"` in the `vnode.data.attrs`, it will appear in the dom as `<input readonly="false">`, which implies that the input is readonly. 
* perf optimization (this change should improve the perf a little bit)
> fixes issue #306 and others: boolean attributes alignment with HTML

- src/tovnode.ts
- test/core.js
This PR is justified on a general level and a specific level.
In general: I believe we don't have a reason to set `vnode.elm` to undefined inside `toVNode()`, no matter what the node is.
In specific: this PR is necessary to support patching inside a DocumentFragment.
> Support DocumentFragment in toVNode()

- .gitignore
- package.json
- tsconfig.json
Modern module bundlers (e.g webpack 3) can generate a more efficient output when working with ES6 modules.
This PR adds the package.json `module` field, which is not standard (yet?) but is now broadly used by the community. See [here](https://github.com/dherman/defense-of-dot-js/blob/master/proposal.md) for detailed info.
This `module` field points to a new directory where the module syntax is ES6 but everything else is ES5. I usually like to separate the two builds into `commonjs` and `es` folders but this would break backward compatibility when importing modules like `snabbdom/modules/props`. I kept the root file structure for the commonjs version so that existing users using commonjs modules are not impacted.
I didn't touch the README as it's been needing some love for a while and that …
> Add package.json/module

- README.md
Docs updates taking #276 into account.
Also improved the explanation on the SVG classList IE bug, with link to caniuse.com, and with new example on a workaround. (BTW, I'm going to fix that classList problem also, in the next weeks)
I assumed the next version would be 0.6.7, and wrote
> The classes in selectors for SVG elements work fine from version 0.6.7.
Please correct me if you are going to make it 0.7.0!
> Update and improve docs section "Using Classes in SVG Elements"

- src/h.ts
I've noticed that `h` [can accept single VNode](https://github.com/snabbdom/snabbdom/blob/56577183e2352fce720c8a993cdc821afa039633/src/h.ts#L32) in position for `children`. I use this feature from time to time, but if I do this in TS environment, `tsc` nags that this is not correct. This PR fixes typings to allow such invocation. Also, I've created a couple of aliases to make code more readable and self-descriptive.
> Improve VNode typings

- src/snabbdom.ts
There is a long discussion about this in https://github.com/snabbdom/snabbdom/issues/348. This PR is a resolution of that discussion.
> fixes issue #348: perf optimization during diffing algo to avoid calling addVNodes and removeVNodes when there is nothing to do

- src/modules/attributes.ts
Casting the setAttribute and setAttributeNS functions at each call site make the code harder to read. Instead extract the new overloads for Element into a global declare statement.
This does not change the generated javascript code,  just makes the typescript easier to read.
> Refactor to remove function casting.

- src/h.ts
In h function, the children variable can be assigned four times (lines 28, 30, 32 and 34) always to an array, making the is.array check in line 37 redundant.
> Remove redundant is.array check in h

- src/modules/style.ts
- test/style.js
This is the fix for the issue https://github.com/cyclejs/cyclejs/issues/747
I assume that modern Chrome (the only browser that failed AFAICT), uses some sort of optimization which causes the transform not to be applied as transition, but as a normal style property and thus not emitting the `transitionend` event.
Apparently using `getComputedStyle().transition` forces the browser to evaluate that
See https://github.com/snabbdom/snabbdom/issues/367#issuecomment-415849750
> Force evaluation of the element stylesheet

- .travis.yml
- browserstack-karma.js
- karma.conf.js
- package.json
- test/index.js
ISSUES FIXED: #396 
Before this can be merged, @paldepind has to activate travis for this repository. I can't finish the travis config until this is done.
Now this allows for easy porting of the tests to typescript
Also this now generates coverage, so there is the possibility of using codecov.io or similar
> Move to karma, allow to test on browserstack

- src/snabbdom.ts
- test/core.js
When patching a text vnode over a vnode with children, the children vnodes must be removed first (so that their hooks are called). The `api.setTextContent` call will end up removing the children elements from the DOM.
> Fix for patching node with text over node with children

- browserstack-karma.js
This PR disables the five browsers that currently fail the tests in the CI setup.
I've only commented them out such that we can easily add them back again if we fix whatever the problems are and/or realize that including them is important.
> Disable failing browsers in CI configuration

- test/style.js
Fixes #447
```
> karma start
05 09 2019 18:35:25.811:INFO [compiler.karma-typescript]: Compiling project using Typescript 3.3.4000
05 09 2019 18:35:31.057:INFO [compiler.karma-typescript]: Compiled 26 files in 5146 ms.
05 09 2019 18:35:32.028:INFO [bundler.karma-typescript]: Bundled imports for 26 file(s) in 469 ms.
05 09 2019 18:35:33.634:INFO [karma-server]: Karma v3.1.4 server started at http://0.0.0.0:9876/
05 09 2019 18:35:33.637:INFO [launcher]: Launching browsers Chrome, Firefox with concurrency unlimited
05 09 2019 18:35:33.655:INFO [launcher]: Starting browser Chrome
05 09 2019 18:35:33.675:INFO [launcher]: Starting browser Firefox
05 09 2019 18:35:36.368:INFO [Chrome 76.0.3809 (Windows 10.0.0)]: Connected on socket Y5ZOZ2SYM9T37QqGAAAA with id 8769878 …
```
> test: use transitionend instead of settimeout

- src/modules/style.ts
Apparently Firefox 70 does not reflow the page with `getComputedStyle().transform` any more. Using `element.offsetLeft` apparently works.
Before this fix:
- [Travis log](https://travis-ci.org/cyclejs/cyclejs/builds/603586313#L749)
- [Browserstack](https://automate.browserstack.com/builds/753fb35ae9eafc6785ea775b0796c29c0eb0f9d5) (ignore the failing chrome 49)
After this fix:
[Browserstack session](https://automate.browserstack.com/builds/f587b63c51112ab8dfd1f67370b7849a7962a250)
<details><summary>Build log from my local test run</summary><p>
```
Scope: current workspace package
> @cycle/dom@22.4.0 test-browser /home/jan/Dokumente/Programmierprojekte/cyclejs/dom
> karma start
27 10 2019 20:42:06.018:INFO [compiler.karma-typescript]: Compiling project using Typescript 3.2.4
27 10 2019 …
```
> Fix element removal on transition end in Firefox70

- README.md
This snippet was added in #287, but it clearly was never tested because it doesn't work (the `underline` class is simply overwritten).
> Replace broken SVG classes example in readme with link to classList polyfill

- .gitignore
- karma.conf.js
- package-lock.json
- package.json
- src/h.ts
- src/jsx-global.d.ts
- src/jsx.ts
- test/core.js
- test/jsx.tsx
- tsconfig.json
Fixes #450 
The h (hyperscript) function is 99% close to being jsx compatible. I acknowledge there is a snabbdom-jsx module, but I think it makes sense to have the built in h function support tsx mode with jsxFactory and babel @jsx pragma. The snabbdom-jsx module supports a lot of bells and whistles which the base h function doesn't really need.
This would make the base h function very usable in typescript projects without adding a lot of fat.
Really hope this isn't rejected outright and we can have some sort of a conversation. I'm a big fan of snabbdom and it's simplicity. This makes snabbdom much more powerful without needing extra modules while still being relatively simple.
**Example**
```tsx
import * as assert from 'assert';
import {h} from '../h';
describe('snabbdom', function() { …
```
> snabbdom can be used with jsx/tsx via jsxFactory: jsx

- src/test/core.ts
And change the name of the existing prop removal test.
Fixes #625.
> test(props): add test for inability to remove native props

- README.md
- src/modules/props.ts
- src/test/core.ts
BREAKING CHANGE: props module does not attempt to delete node
properties. This may affect you if you are using the props module
to add non-native (custom) properties to DOM nodes. Instead, it is
recommended to use _data-* attributes_.
https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes
Fixes #623.
Fixes #283.
Closes #415.
Closes #307.
Closes #151.
Closes #416.
> fix(props): do not attempt to delete node properties

- commitlint.config.json
- src/modules/attributes.ts
BREAKING CHANGE: Types exported by this package have re-declared
the global `Element.setAttribute` and `Element.setAttributeNS` to
accept `number` and `boolean` for the `value` parameter. This
change removes that re-declaration and thus the only valid value is
`string`. If your code provides `number` and/or `boolean`, then it
may now fail to compile.
Fixes #615.
> fix(attrs): do not redeclare Element.setAttribute(NS)

- README.md
It looks like there is two imports with no reasons for this
> Removed duplicate 'h' import in README.md

- src/package/modules/eventlisteners.ts
- src/test/unit/eventlisteners.ts
BREAKING CHANGE: loaded/carrying event listeners are no longer supported.
For alternatives see issue #802.
Fixes #802
> feat(eventlisteners): remove loaded listeners feature

- README.md
Motivation: I recently tried using the JSX pragma in a project and it wasn't clear why Snabbdom wasn't processing my element props via the appropriate module (class, style, props, attributes, etc). But I eventually figured it out, and figured it'd be worth adding here.
Main additions are:
- adds JSX examples to module sections
- removes file extension requirement in babel config section (babel only cares about the pragma, not the extension, to my knowledge).
Is it worth adding these? Should there be other clarifications/additions I didn't cover? Thanks.
> docs: add additional JSX usage information

- README.md
- src/h.ts
- src/htmldomapi.ts
- src/index.ts
- src/init.ts
- src/vnode.ts
- test/unit/core.ts
This pull request introduces an ability to handle [`DocumentFragment`](https://developer.mozilla.org/docs/Web/API/DocumentFragment), which is another notable subclass of [`Node`](https://developer.mozilla.org/en-US/docs/Web/API/Node) other than [`Element`](https://developer.mozilla.org/docs/Web/API/Element) nor [`Text`](https://developer.mozilla.org/docs/Web/API/Text).
It allows a function to return multiple VNodes without an extra wrapper element, resolving #560.
`fragment` function is now exported from the entry point.
There is, however, a room for discussion on the design of the API.
The second commit will allow us to use a `DocumentFragment` as a container, in addition to an `Element`.
In the current implementation I chose a2), but of course it's okay to change it along with the …
> Support DocumentFragment

- README.md
- src/index.ts
- src/jsx.ts
- test/tsconfig.json
- test/unit/jsx.tsx
Addresses #560
Added support for JSX fragments.
A fragment can be created with `<>...</>`, and it will be converted into a VNode without `sel`.
Please check the test cases to see how it works.
(In fact they are almost copy-and-paste from ones for `jsx` function, but looks reasonable for me.)
> Support JSX fragments

- src/index.ts
- src/init.ts
This is a speculative pull request addressing https://github.com/snabbdom/snabbdom/pull/975#issuecomment-997180772, so please feel free to close this if you don't need this.
---
Exporting the `Options` type, so that other libraries in the ecosystem (e.g. `@cycle/dom`) can depend on it.
> Export `Options` type from the entry point

- src/htmldomapi.ts
- src/init.ts
- test/unit/core.ts
Fix for the bug mentioned on https://github.com/snabbdom/snabbdom/issues/1014.
To fix the bug, it was needed to keep the Ref of the parent that the `DocumentFragment` was appended to. So the easiest fix was to create a `parent` property on fragment ref inside the `insertBefore` hook (maybe we'll need to add it to other domApi hooks too, but it's working just with this one).
The tests for fragment patch weren't right, even with success it was bugging on real browsers. So I fixed the tests to reproduce the bug.
I will be happy to help with any questions that come out.
> fix(fragment): fixed patching fragment nodes

- README.md
Thank you for maintaining snabbdom.
A small fix to make the README's example compilable by default when copy-pasting.
Feel free to close if too niche.
> NIT: fix README's example

- .github/workflows/steps.yml
Specify actions/checkout@v3 for ci tests and remove empty newlines. [V3 is the newer version][0] using node16 runtime,
```diff
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
```
[0]: https://github.com/actions/checkout/compare/v2.4.2...v3.0.2#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R17-R18
> chore(test): use actions/checkout@v3, replacing v2

- web-test-runner.config.js
closes https://github.com/snabbdom/snabbdom/issues/1059
> chore(test): use default concurrency 1, so local unit tests do not hang

- package.json
`npm publish --dry-run` before this change
```bash
npm notice === Tarball Details === 
npm notice name:          snabbdom                                
npm notice version:       3.5.1                                   
npm notice filename:      snabbdom-3.5.1.tgz                      
npm notice package size:  89.8 kB                                 
npm notice unpacked size: 387.6 kB                                
npm notice shasum:        e1e33224b1397bc6633a3cff1c8af718da612c01
npm notice integrity:     sha512-FDUepV7ay0KHD[...]W2N0zF8lSXffg==
npm notice total files:   116
```
`npm publish --dry-run` after this change
```bash
npm notice === Tarball Details === 
npm notice name:          snabbdom                                
npm notice version:       3.5.1 …
```
> chore(tools): use npm files directive for smaller publish size

- README.md
```diff
diff --git a/README.md b/README.md
index 1d72a15..92038f9 100644
--- a/README.md
+++ b/README.md
@@ -1,4 +1,4 @@
-<img alt="Snabbdom" src="readme-title.svg" width="356px">
+<img alt="Snabbdom" src="https://i.imgur.com/4Bq0tyi.png" width="356px">
A virtual DOM library with a focus on simplicity, modularity, powerful features
and performance.
```
This PR updates the image reference in the README from a relative image path to an imgur image url, and the reason for the change is discussed at the [bottom of this PR](https://github.com/snabbdom/snabbdom/pull/1063#issuecomment-1781595164)
imgur does not support svg. To preserve as much fidelity as possible, the image was imported to inkscape, scaled down to the README's 356px and then exported to PNG
> chore(docs): reference readme-title image from imgur

- src/modules/attributes.ts
- test/unit/attributes.ts
closes https://github.com/snabbdom/snabbdom/issues/1049
Node's runtime appeared to be unfarily optimising part the benchmark test for the original charCodeAt implementation. The final benchmark was updated to more closely resemble the actual behaviour of snabbdom. The final benchmark test and results are attached.
<details>
<summary>benchmark</summary>
```javascript
// $ node ~/software/performance.js
const common = require('./node/benchmark/common.js');
const bench = common.createBenchmark(main, {
n: [1000000000],
type: [
'charCodeAt',
'charCodeAtV2'
],
string: ['svg:test', 'xmlns:test', 'nonamespace']
});
function main(conf) {
const string = conf.string
const type = conf.type
const set = (res, o = {}) => {
o[res] = res
return o
}
if (type === 'charCodeAt') {
const colonChar = 58; …
```
> fix: patching namespaced attributes (#1049)

- .github/workflows/steps.yml
https://github.com/actions/checkout/releases/tag/v4.0.0
The previous PR should have updated this to v4 rather than v3
> chore(test): use actions/checkout@v4, replacing v3

- .github/workflows/publish.yml
This job publishes snabbdom to github's npm package repository and it will only run when a release is created. Github's package repository requires packages to be "scoped". Un-scoped package names like "snabbdom" need to have a scope added to them, so this part applies a scope to the name before publishing, so the published name becomes "@snabbdom/snabbdom"
```javascript
const fs = require('fs').promises;
fs.readFile('package.json', 'utf8').then((data) => JSON.parse(data)).then((json) => {
json.name = '@$(echo "$GITHUB_REPOSITORY" | sed 's/\/.\+//')/' + json.name;
console.info('Package name changed to %s', json.name);
return fs.writeFile('package.json', JSON.stringify(json), 'utf8');
}).catch(error => {
console.error(error);
process.exit(1);
});
```
An example package published to …
> chore(tools): added github package publishing job, runs when release is created

- package-lock.json
- package.json
This PR removes the cross-env devDependency, which is un-maintained. Snabbdom sources do not appear to use cross-env anywhere,
* https://www.npmjs.com/package/cross-env
* https://packagephobia.com/result?p=cross-env
> chore(tools): remove devdependency cross-env; un-maintained, not used ~86kB

- .github/workflows/test.yml
- README-in_HN.md
- README-zh_CN.md
- README.md
This PR renames the ci job from CI to test-browser. The reason for doing this is to later differentiate between "test-browser" and "test-node" in a future event where tests may run using a node runtime and jsdom https://github.com/snabbdom/snabbdom/issues/1050
> chore(test): rename ci job from CI to test-browser

- .github/workflows/lint.yml
- package.json
Later, prettier format-check can be enabled to require all files pass lint and prettier format-check at the ci pipeline for each PR
```diff
diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
index 5e0148e..1b99b44 100644
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -12,5 +12,5 @@ jobs:
steps:
- uses: actions/checkout@v4
- run: npm install
-    # - run: npm run format-check
+    - run: npm run format-check
- run: npm run lint
```
> chore(tools): add lint job to ci pipeline

- src/init.ts
- test/unit/core.ts
closes https://github.com/snabbdom/snabbdom/issues/972
closes https://github.com/snabbdom/snabbdom/issues/971
Feel free to leave criticism. Changes are not smoke-tested, however all unit-tests are passing.
Some parts of createElm were rearranged to support these scenarious,
* `vnode("", {}, [], "Test Text 1", null)` if there is no selector, a textNode is created as one of the first conditions
* `vnode("h1", {}, [], "Test Text h1", null)` if there is a selector, a primitive vnode text AND an empty child list, a textNode is childed to the element
> fix: patch should apply textNodes (#972)

- package.json
Currently our `package.json` says minimum node engine version is `8`, but we have `"type": "module"` in our `package.json` and that requires node v12+ as per https://nodejs.org/dist/latest-v20.x/docs/api/esm.html#modules-ecmascript-modules
> fix: correct minimum node version to one that supports modules

- src/jsx.ts
- src/modules/style.ts
- src/vnode.ts
- Use lib.dom's `HTMLTagNameMap` for HTML element property names in JSX
- Use lib.dom's `ElementCSSInlineStyle` for style property names in all VNodes
The meta-typing for HTML element property names could also be applied to `h` overloads as well and more VNode situations in general (`HTMLTagNameMap` exists for mapping overloads to among other things `document.createElement(elementName: string)`) but I didn't already have a working equivalent on hand, I just had the JSX specific types, so that isn't included in this PR.
This was JSX meta-typing that I discovered/built for [Butterfloat](https://worldmaker.net/butterfloat/), but having used Snabbdom in the past and may use Snabbdom in the future I thought would be useful to share the meta-programming wealth for better auto-complete in more …
> Enhance JSX and VNode types

- README.md
This PR updates the first README example to use the attributesModule, to increase the chance of success for people who start by copy-pasting the README example.
Related https://github.com/snabbdom/snabbdom/pull/1066
> chore(docs): add attributesModule to first README example (#958)

- .github/workflows/lint.yml
- .github/workflows/publish.yml
This ensures that exactly the versions specified in the `package-lock.json` is used when running the CI.
> Use npm ci instead of npm install

- src/modules/style.ts
essentially, this is the same as https://github.com/snabbdom/snabbdom/pull/885
> fix: detect window.requestAnimationFrame function before calling

- src/modules/dataset.ts
- src/modules/style.ts
- test/unit/dataset.ts
- test/unit/style.ts
This PR fixes an issue where falsy values such as `0` or `""` where accidentally being removed by the dataset and styles module during diffing.
ISSUES CLOSED: #303, #1093
> Handle falsy values correctly in the dataset and style modules

- README.md
Document the selector better and mention that it is used to determine vnode "sameness" as pointed out in #333.
Closes #333
> Document the selector property and its use in identifying nodes

- src/init.ts
- test/unit/core.ts
This changes the child reordering patch process slightly. Before beginning to move elements around we add an extra case where we check if the end of the new remaining vnodes is brand new and could thus be handled by inserting a new DOM node.
This should address and close #1099.
> Detect opportunity to insert new vnode earlier for more efficient DOM manipulation

- README-in_HN.md
- README-zh_CN.md
- README.md
- examples/hero/hero.js
- examples/reorder-animation/index.js
- perf/benchmarks.js
- src/init.ts
- src/modules/style.ts
- test/unit/attachto.ts
- test/unit/attributes.ts
- test/unit/core.ts
- test/unit/dataset.ts
- test/unit/eventlisteners.ts
- test/unit/htmldomapi.ts
- test/unit/jsx.tsx
- test/unit/style.ts
- test/unit/thunk.ts
This PR refactors Snabbdom to use modern JavaScript features in more places.
Note, that most of the changes are simply from using arrow functions, which causes a lot of line changes in the tests. The only "interesting" changes are in `src/init.ts`.
The PR also removes the `isUndef` and `isDef` functions. I think those functions where worth it back before the optional operators, where Snabbdom needed to dig into deep paths with optional values at every level, but today I don't think those functions are justified.
> Use modern JS features in additional places

- src/jsx.ts
Typescript intellisense appears to have been broken by #1052. For example:
```tsx
<div>Hello, world!</div>
```
The above code generates `ts(7026)`: `JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists.` This is because as of #1052, `src/jsx.ts` no longer exports the `JSX` namespace within the parent `jsx` namespace, since the tsconfig option `isolatedModules` doesn't support the `import export` syntax that was used for this previously.
This pull request contains a workaround that avoids `import export`, but still allows the `JSX` namespace to be exported, so that `isolatedModules` can be set, but Typescript intellisense also works.
> Restore Typescript intellisense
